version: "3.8"
services:
  backend:
    build: .
    container_name: landing-bNs
    ports:
      - "5070:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -lc "corepack enable && pnpm i && pnpm dev"
